/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UIRegister;


import info5100.university.example.Department.Department;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sunzuolin
 */
public class RegisterWorkArea extends javax.swing.JPanel {
JPanel mainpanel;
Department department;
    /**
     * Creates new form RegistrarWorkArea
     */
    public RegisterWorkArea(JPanel mainpanel,Department department) {
        initComponents();
        this.mainpanel=mainpanel;
        this.department=department;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCourseOfferingManagement = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnFiancialMonitoring = new javax.swing.JButton();
        btnAnalyticsReport = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Register Work Area");

        btnCourseOfferingManagement.setText("Course Offering Management");
        btnCourseOfferingManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseOfferingManagementActionPerformed(evt);
            }
        });

        btnStudentRegistration.setText("Student Registration");
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        btnManageProfile.setText("Manage  Profile");
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnFiancialMonitoring.setText("Financial Monitoring");
        btnFiancialMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiancialMonitoringActionPerformed(evt);
            }
        });

        btnAnalyticsReport.setText("Analytics Report");
        btnAnalyticsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAnalyticsReport, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourseOfferingManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFiancialMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseOfferingManagement)
                    .addComponent(btnStudentRegistration))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiancialMonitoring)
                    .addComponent(btnManageProfile))
                .addGap(54, 54, 54)
                .addComponent(btnAnalyticsReport)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseOfferingManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseOfferingManagementActionPerformed
        // TODO add your handling code here:
     /*   CourseOfferingManagementJPanel comJPanel=new CourseOfferingManagementJPanel( mainpanel, business);
        mainpanel.add(" CourseOfferingManagementJPanel",comJPanel);
        
        CardLayout layout = (CardLayout) mainpanel.getLayout();
            layout.next(mainpanel);*/
    }//GEN-LAST:event_btnCourseOfferingManagementActionPerformed

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
       /*  StudentRegistrationJPanel srJPanel=new StudentRegistrationJPanel( mainpanel, business);
        mainpanel.add(" StudentRegistrationJPanel",srJPanel);
        
        CardLayout layout = (CardLayout) mainpanel.getLayout();
            layout.next(mainpanel);*/
    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
     /*   ManageProfileJPanel mpJPanel=new ManageProfileJPanel( mainpanel, business);
        mainpanel.add(" ManageProfileJPanel",mpJPanel);
        
        CardLayout layout = (CardLayout) mainpanel.getLayout();
            layout.next(mainpanel);*/
    }//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnFiancialMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiancialMonitoringActionPerformed
        // TODO add your handling code here:
      /*  FinancialMonitoringJPanel fmJPanel=new FinancialMonitoringJPanel( mainpanel, business);
        mainpanel.add(" FinancialMoitoringJPanel",fmJPanel);
        
        CardLayout layout = (CardLayout) mainpanel.getLayout();
            layout.next(mainpanel);*/
    }//GEN-LAST:event_btnFiancialMonitoringActionPerformed

    private void btnAnalyticsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsReportActionPerformed
        // TODO add your handling code here:
       /*  AnalyticsReportJPanel arJPanel=new AnalyticsReportJPanel( mainpanel, business);
        mainpanel.add(" AnalyticsReportJPanel",arJPanel);
        
        CardLayout layout = (CardLayout) mainpanel.getLayout();
            layout.next(mainpanel);*/
    }//GEN-LAST:event_btnAnalyticsReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyticsReport;
    private javax.swing.JButton btnCourseOfferingManagement;
    private javax.swing.JButton btnFiancialMonitoring;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
