/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example;



import info5100.university.example.Persona.AdmainProfile;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Profile;
import info5100.university.example.Persona.RegistrarProfile;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Persona.UserAccount;
import info5100.university.example.Persona.UserAccountDirectory;
import info5100.university.example.UIRegistrar.RegistrarWorkArea;
import info5100.university.example.UIadmin.AdmainWorkArea;
import info5100.university.example.UIfaculty.FacultyWorkArea;
import info5100.university.example.UIstudent.StudentWorkArea;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sunzuolin
 */
public class Log extends javax.swing.JPanel {
Business business;
  JPanel MainPanel;
    /**
     * Creates new form Log
     */
    public Log(JPanel MainPanel, Business business) {
        initComponents();
        this.MainPanel = MainPanel;
        this.business = ConfigureTheBusiness.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("University  Login");

        jLabel2.setText("UserName");

        jLabel3.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(69, 69, 69)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(72, 72, 72)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(btnLogin)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(47, 47, 47)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(57, 57, 57)
                    .addComponent(btnLogin)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUserName.getText();
        String userpassword = txtPassword.getText();
        UserAccountDirectory uad = business.getUseraccountdirectory();
        UserAccount ua = uad.AuthenticateUser(username, userpassword);
        if (ua == null) {
            return;
        }
        AdmainWorkArea admainworkarea;
        StudentWorkArea studentworkarea;
        FacultyWorkArea facultyworkarea;
        RegistrarWorkArea registarworkarea;
        String r = ua.getRole();
        Profile profile= ua.getAssociatedPersonProfile();
        if (profile instanceof StudentProfile) {

            StudentWorkArea panel = new StudentWorkArea(MainPanel,business);

            MainPanel.add("StudentWorkArea", panel);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.next(MainPanel);
        }

        if (profile instanceof FacultyProfile) {

            FacultyWorkArea panel = new FacultyWorkArea(MainPanel,business);
            MainPanel.add("FacultyWorkArea", panel);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.next(MainPanel);
        }

        if (profile instanceof AdmainProfile) {

            AdmainWorkArea panel = new AdmainWorkArea(MainPanel,business);
            MainPanel.add("AdmainWorkArea", panel);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.next(MainPanel);
        }
        if (profile instanceof RegistrarProfile) {

            RegistrarWorkArea panel = new RegistrarWorkArea(MainPanel,business);
            MainPanel.add("RegistrarWorkArea", panel);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.next(MainPanel);
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
